### ISSUE TITLE
Add interface for reading sample rate of acceleration. 

### ISSUE THREAD

**Issue by gerber4** [NeoBirth/accelerometer.rs#52]
It could be valuable to add an interface for reading rate of acceleration. This would be valuable for creating libraries that use an accelerometer. For example, with timing data I could begin calculating the position of the device based on acceleration.

**Comment by gerber4** [comment]
What would be a good agnostic format for the sample_rate method? It could be exposed as a u32 or f32 representing hz.

**Comment by tarcieri** [comment]
@JosephBGerber a raw `u32` or a `Hertz` newtype maybe? (guess you went with an `f32` on your PR?)

**Comment by gerber4** [comment]
I feel that an f32 is a good choice due to the existence of fractional frequencies and the usage in further calculations.

**Comment by tarcieri** [comment]
Resolved by #53
