### ISSUE TITLE
e-Compass

### ISSUE THREAD

**Issue by rubberduck203** [NeoBirth/accelerometer.rs#63]
Not an issue with this crate. 
I was just hoping you may have some insight and this was the easiest way to contact you. 

Are you aware of any similar efforts for magnoneters?
I’m eventually imagining a similar crate, building off this one, to create a `Compass` trait. 
e-Compasses that have both an accelerometer and magnometer on board are fairly common.
Are you aware of any efforts in this space?

**Comment by tarcieri** [comment]
Unfortunately I haven't really kept up in this space and would really like to hand this crate off to someone who can take proper care of it.

I've seen various magnetometer/AHRS projects in Rust in the past though, perhaps most notably https://github.com/japaric/madgwick

**Comment by rubberduck203** [comment]
That’s fair enough. 
It was worth asking. 
Thanks for taking the time to get back to me and the effort that’s gone into this crate. 

I maintain the `stm32f3-discovery` board support crate. There was recently a revision that changed the accelerometer on it and the `Accelerometer` trait is going to make it an easier transition for my users, so I really do appreciate the work you’ve done.
